app:
  port: 8080
  jwt_secret: thisisjustmysecretkeys2024
database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: your_db
logging:
  elk_host: "localhost:9200"
  apm_host: "localhost:8200"